### ISSUE TITLE
Solve the bonus part in Section 1 > Assignments > A4

### ISSUE THREAD

**Issue by proffapt** [proffapt/iitkgp-pds-lab#1]
Link to the problem statement: https://github.com/proffapt/iitkgp-pds-lab/blob/main/Section_01/Assignments/A4/A4.pdf

Link to incomplete code attempt and idea: https://github.com/proffapt/iitkgp-pds-lab/blob/main/Section_01/Assignments/A4/bonus.c

Limitations:
1) Only Arrays are allowed and anything traditionally and technically advance than it is NOT allowed.
2) No ADT.

**Comment by Atharva-Thakur** [comment]
Please assign it to me

**Comment by proffapt** [comment]
Great!
Assigning.. best of luck!

**Comment by proffapt** [comment]
UPDATE: array was allowed during this assignment so you can use arrays.

**Comment by proffapt** [comment]
Closing this issue, as this is not in my interest anymore
